name: Bartender Dry Run
on:
  workflow_dispatch:
    inputs:
      bartender_command:
        description: 'Bartender CLI command'
        required: true
        default: '-v'
      user:
        description: 'Id of slack user which triggered this workflow'
        required: true
        default: 'U020CNBGDQA'
        
jobs:
  user:
    name: ${{ github.event.inputs.user}}
    runs-on: ubuntu-latest
    steps:
      - name: Print user
        run: echo ${{ github.event.inputs.user}}
  run:
    name: ${{ github.event.inputs.bartender_command }}
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v2
      - name: Add secrets.config
        run: sudo touch /usr/local/etc/secrets.config
      - name: Make user own secrets.config
        run: sudo chown $USER /usr/local/etc/secrets.config
      - name: Add secrets to config for integration tests
        run: |
          echo "BUILD_AWS_SECRET_ACCESS_KEY=${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}" >> /usr/local/etc/secrets.config
          echo "UAT_AWS_SECRET_ACCESS_KEY=${{ secrets.UAT_AWS_SECRET_ACCESS_KEY }}" >> /usr/local/etc/secrets.config
          echo "PROD_AWS_SECRET_ACCESS_KEY=${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}" >> /usr/local/etc/secrets.config
          echo "GITHUB_PAT=${{ secrets.BARTENDER_PAT }}" >> /usr/local/etc/secrets.config
      - name: Install PyGithub
        run: sudo pip3 install PyGithub==1.55
      - name: Install latest bartender binary
        run: sudo bash ./scripts/install_latest_bartender.sh
      - name: Execute bartender command
        run: ./${{ github.event.inputs.bartender_command }} -D -d -s 2>&1 | tee output.txt
      - name: Set release file path
        id: relfile
        run: | 
          echo "::set-output name=REL_FILE_PATH::$(echo $(tail -1 output.txt) | python3 -c 'import json,sys;obj=json.load(sys.stdin);print(obj["rel_file_path"])')"     
      - name: Upload dry run release file
        uses: actions/upload-artifact@v2
        with:
          name: bartender-command-output
          path: ${{ steps.relfile.outputs.REL_FILE_PATH }}
  output:
    runs-on: ubuntu-latest
    needs: [user, run]
