name: Bartender
on:
  repository_dispatch:
    types:
      - bartender
jobs:
  run:
    name: Run bartender
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v2
      - name: Make sure /usr/etc exists
        run: sudo mkdir -p /usr/etc
      - name: Add secrets.config
        run: sudo touch /usr/etc/secrets.config
      - name: User own file 
        run: sudo chown $USER /usr/etc/secrets.config
      - name: Add secrets to config for integration tests
        run: |
          echo "BUILD_AWS_SECRET_ACCESS_KEY=${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}" >> /usr/etc/secrets.config
          echo "UAT_AWS_SECRET_ACCESS_KEY=${{ secrets.UAT_AWS_SECRET_ACCESS_KEY }}" >> /usr/etc/secrets.config
          echo "PROD_AWS_SECRET_ACCESS_KEY=${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}" >> /usr/etc/secrets.config
          echo "GITHUB_PAT=${{ secrets.BARTENDER_PAT }}" >> /usr/etc/secrets.config
      - name: debug
        run: pwd && ls
      - name: Install latest bartender binary
        run: sudo bash ./scripts/install_latest_bartender.sh
      - name: Execute bartender command
        run: echo bartender ${{ github.event.client_payload.bartender_input }} 
