name: Bartender Dry Run
on:
  workflow_dispatch:
    inputs:
      bartender_command:
        description: 'Bartender CLI command'
        required: true
        default: '-v'
      release_manager:
        description: 'Id of slack user which triggered this workflow'
        required: true
        default: 'U020CNBGDQA'
        
jobs:
  upload-workflow-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Store inputs in file
        env:
          WORKFLOW_INPUTS: ${{ toJSON(github.event.inputs) }}
        run: echo "$WORKFLOW_INPUTS" > /tmp/inputs.json
      - name: Upload inputs artifact
        uses: actions/upload-artifact@v2
        with:
          name: workflow-inputs
          path: /tmp/inputs.json
  run-bartender:
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v2
      - name: Add secrets.config
        run: sudo touch /usr/local/etc/secrets.config
      - name: Make user own secrets.config
        run: sudo chown $USER /usr/local/etc/secrets.config
      - name: Add secrets to config for integration tests
        run: |
          echo "BUILD_AWS_SECRET_ACCESS_KEY=${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}" >> /usr/local/etc/secrets.config
          echo "UAT_AWS_SECRET_ACCESS_KEY=${{ secrets.UAT_AWS_SECRET_ACCESS_KEY }}" >> /usr/local/etc/secrets.config
          echo "PROD_AWS_SECRET_ACCESS_KEY=${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}" >> /usr/local/etc/secrets.config
          echo "GITHUB_PAT=${{ secrets.BARTENDER_PAT }}" >> /usr/local/etc/secrets.config
      - name: Install PyGithub
        run: sudo pip3 install PyGithub==1.55
      - name: Install latest bartender binary
        run: sudo bash ./scripts/install_latest_bartender.sh
      - name: unzip bartender binary [REMOVE ME]
        run: unzip bartender.zip
      - name: Execute bartender command [REMOVE ME ./]
        run: |
          ./${{ github.event.inputs.bartender_command }} -D -d -s 2>&1 | tee outputs.txt
          echo $?
      - name: Set release file path
        id: relfile
        run: | 
          echo ::set-output name=path::$(echo $(tail -1 outputs.txt) | python3 -c 'import json,sys;obj=json.load(sys.stdin);print(obj["release_file"]["path"])')    
      - name: Upload dry run release file
        uses: actions/upload-artifact@v2
        with:
          name: bartender-dry-run-relfile
          path: ${{ steps.relfile.outputs.path}}
